[development]
address = "127.0.0.1"
port = 8888
workers = 4
log = "normal"

[staging]
address = "0.0.0.0"
port = 80
workers = 4
log = "normal"

[production]
address = "0.0.0.0"
port = 80
workers = 4
log = "critical"
