name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup toolchain (nightly)
      run: |
        rustup toolchain add nightly
        rustup override set nightly
    - name: Run tests
      run: |
        cargo check --verbose
        cargo test --verbose
